/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dependencies from "./dependencies";
export type { dependencies };
import type * as flashloan from "./flashloan";
export type { flashloan };
import type * as interfaces from "./interfaces";
export type { interfaces };
